pom.xml

As we already discussed in chat `org.semver.Version$Special` had issues with equals which we had to resolve to fix `Verison` clients unit tests - the thing is this project is archived in github so we decided to fork it to implement the fix.
So this PR is about starting to use this fix in strongbox. This is a prerequisite for https://github.com/strongbox/strongbox/issues/611

Use snapshot version of org.semver where we implemented fixes necessary for strongbox#611

---

pom.xml

Fixes #1096.
Move dependency exclusions from children to the `strongbox-parent`.
Changed spring-boot-test to `spring-boot-starter-test`, as this is a superset of spring-boot-test, and moves it out of `strongbox-web-core`.

Issue-1096: Move dependency exclusions from children to parent pom

---

pom.xml

Updates gmavenplus-plugin version to 1.6 so we can benefit from execute goal scripts provided as direct paths. This is a prerequisite to fix [#1157](https://github.com/strongbox/strongbox/issues/1157)

Updates gmavenplus-plugin version to 1.6

---

pom.xml

As part of implementation of https://github.com/strongbox/strongbox/issues/1124, add dependency information for springfox-swagger.

Add dependencies for springfox-swagger

---

pom.xml

Fixes strongbox/strongbox#1255.

Issue-1255: Upgrade the version of Jetty.

---

pom.xml

Upgraded to `org.quartz-scheduler:quartz:2.3.1` and `com.mchange:c3p0:jar:0.9.5.4`.
Fixes strongbox/strongbox#1263.
Requires follow-up in strongbox/strongbox#1130.

Issue 1263: Upgrade com.mchange:c3p0 to version 0.9.5.4 or higher

---

pom.xml

Fixes strongbox/strongbox#1285.
Tasks carried out:

Issue-1285: Upgrade to Jackson 2.9.9

---

pom.xml

Fixes [strongbox #1565](https://github.com/strongbox/strongbox/issues/1565#issue-513023450)
Sorry for late PR, spent some time trying to make the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) work on my local environment. I couldn't find any `catalina` dependency in the [strongbox](https://github.com/strongbox/strongbox/) project so only update other two projects. The tests all passed successfully on my machine after dropping this dependency.

Drop the org.apache.tomcat:catalina dependency

---

pom.xml

Related to strongbox/strongbox#1397.
This PR should be merged at the same time as PR strongbox/strongbox#1474.

Issue-1397: Upgrade commons-http to version 1.3 and commons-io to 1.1.

---

pom.xml

* Added an exclusion for `org.springframework.boot:spring-boot-starter-tomcat` from the `org.springframework.boot:spring-boot-starter-web`, as we're not using Tomcat.

Added org.redline-rpm:redline:1.2.9

---

pom.xml

Fixes strongbox/strongbox#1864
To add maven-enforce plugin to check for the required 3.6.3 maven version

Issue-1864: Add a rule using the maven-enforcer plugin that requires Maven 3.6.3

---

pom.xml

This pull request closes strongbox/strongbox#1874

Issue 1874: Upgrade the org.codehaus.mojo:build-helper-maven-plugin from 1.9.1 to 3.2.0

---

pom.xml

This PR addresses [#Issue-1857](https://github.com/strongbox/strongbox/issues/1857)
Incremented swagger core version from 1.5.18 to 1.6.2.

Issue-1857: Upgrade swagger dependencies from 1.5.18 to 1.6.2

---

pom.xml

This pull request closes strongbox/strongbox#1910

Issue 1910: Upgrade our Jersey dependencies from 2.23.1 to 2.32

---

pom.xml

Related to issue strongbox/strongbox#1853.
This PR should be merged before the PR strongbox/strongbox/pull/1890

Issue 1853: Upgrade our hamcrest dependencies from 1.3 to 2.2

---

pom.xml

This pull request closes strongbox/strongbox#1860

Issue-1860: Update commons-fileupload:commons-fileupload from 1.3.3 to 1.4

---

pom.xml

This pull request closes strongbox/strongbox#1861

Issue 1861: Upgrade commons-io:commons-io from 2.6 to 2.8.0

---

pom.xml

This pull request closes strongbox/strongbox#1848

Issue 1848: Upgrade Jetty to 9.4.33.v20201020

---

pom.xml

- Upgraded plugin versions and changed project version
This pull request closes strongbox/strongbox/issues/1870  

Issue 1870: Upgrade the maven-surefire-plugin and maven-failsafe-plugin to 3.0.0-M5

---

pom.xml

- Upgrade the maven-resources plugin from 3.0.2 to 3.2.0
This pull request closes strongbox/strongbox#1871

Issue 1871: Upgrade the maven-resources-plugin from 3.0.2 to 3.2.0

---

pom.xml

It seems there is some sort of bug with the `maven-dependency-plugin` that causes a 401 when deploying to the repository through Jenkins. Reverting this to `2.8.2`. This is caused by [MDEPLOY-244](https://issues.apache.org/jira/browse/MDEPLOY-244).
This pull request closes strongbox/strongbox#

Issue 1942: Add explicit versions for the plugins that are missing such in the strongbox-parent
