pom.xml
Reverts strongbox/strongbox-parent#1
=> Revert "orientdb upgrade from 3.0.0 to 3.0.13"

pom.xml
=> SB-1266: PropertiesBooter improvements

pom.xml
Necessary dependency for strongbox/strongbox#1023.
=> SB-1266: Add spring-boot-test dependency.

pom.xml
Fixes strongbox/strongbox#1096.
@carlspring 
Please review.
=> Issue 1096: Cleanup the pom.xml files from dependency exclusions and extract them to the strongbox-parent

pom.xml
Reverts strongbox/strongbox-parent#9
=> Revert "Issue 1096: Cleanup the pom.xml files from dependency exclusions and extract them to the strongbox-parent"

pom.xml
Fixes strongbox/strongbox#1016.
=> Issue-1016: Update junit-jupiter and junit-platform versions

pom.xml
Partial dependencies stabilization.
This issue relates to strongbox/strongbox#1130.
=> Issue-1130: Stabilize our dependencies

pom.xml
Removes redundant jnuget dependencies.
Fixes [#1131](https://github.com/strongbox/strongbox/issues/1131).
=> Remove redundant jnuget dependencies

pom.xml
Fixes strongbox/strongbox#1254.
=> Issue-1254: Upgrade to spring-boot 2.1.5.RELEASE

pom.xml
Fixes strongbox/strongbox#1262.
=> Issue-1262: Upgrade to commons-collections4.

pom.xml
Reverts strongbox/strongbox-parent#28
=> Revert "maven-commons-1.6"

pom.xml
This issue relates to:
strongbox/strongbox#1109
strongbox/strongbox#1130
=> issue-1109 update aspectj version to work with jdk 9

pom.xml
This is related to strongbox/strongbox#1420
=> issue-1420 Adding rxjava dependency

pom.xml
Related to: https://github.com/strongbox/strongbox/pull/1485
=> Issues-1456: Exclude hamcrest from parent

pom.xml
This PR closes https://github.com/strongbox/strongbox/issues/1484
=> issues/1484 Upgrade commons-io to version 2.6 and use junit-bom

pom.xml
Fixes: https://github.com/strongbox/strongbox/issues/1390
=> Issue-1390: Upgrade to Jackson >= 2.9.9.1

pom.xml
Fixes strongbox/strongbox#1493
Work in progress pls don't marge
=> Issue-1493 Upgraded hibernate.validator to newest version 6.0.17.Final

pom.xml
Closes https://github.com/strongbox/strongbox/issues/1528
=> Bump apache commons-compress from 1.18 to 1.19

pom.xml
Fixes strongbox/strongbox#1547.
=> Excluding "org.testng:testng"

pom.xml
Fixes strongbox/strongbox#1563.
=> Issue 1563: Clean up properties in the strongbox-parent

pom.xml
#49 https://github.com/strongbox/strongbox/issues/1562
=> Removed maven-war-plugin from strongbox-parent pom.xml

pom.xml
#54 https://github.com/strongbox/strongbox/issues/1566
=> Upgrade awaitility version to 4.0.1

pom.xml
Fix as a part of https://github.com/strongbox/strongbox/issues/1656
=> Issue 1656: Upgrade version of spring boot from 2.1.5.RELEASE to 2.2.4.RELEASE (to update spring-web-mvc version to 5.2.3)

pom.xml
This pull request closes strongbox/strongbox#1711 .
=> Issue 1711: Fix org.vafer:jdeb plugin

pom.xml
This PR fixes https://github.com/strongbox/strongbox/issues/1781
=> Issue-1781 :: Upgrading httpclient and jersey version to fix

pom.xml
Upgraded dependency version. Ran all tests successfully. https://github.com/strongbox/strongbox/pull/1880 depends on this pull request.
=> Issue#1878: Upgrade the org.jacoco:jacoco-maven-plugin

pom.xml
Resolved strongbox/strongbox#1872
Passed all the tests following "Steps For Upgrading Dependencies And Plugins".
=> issue-1872: Upgrade the maven-jar-plugin from 3.0.2 to 3.2.0

pom.xml
Upgraded dependency version. Ran all tests successfully.
This will resolve [#1850](https://github.com/strongbox/strongbox/issues/1850).
=> Issue#1850: Upgrade our slf4j dependencies from 1.7.24 to 1.7.30

pom.xml
Fixes strongbox/strongbox#1875.
=> Upgrade the maven-source-plugin from 2.2.1 to 3.2.1 #1875

pom.xml
Fixes strongbox/strongbox#1876.
=> issue-1876: Upgrade the maven-enforcer-plugin from 3.0.0-M1 to 3.0.0-M3

.github/PULL_REQUEST_TEMPLATE.md
Fixes strongbox/strongbox#1901.
=> Issue 1901: Copy our pull request template to the rest of the Strongbox projects

pom.xml
Addressing the Awaitility dependency upgrade.
Fixes strongbox/strongbox#1856.
=> Issue 1856: Upgrade our awaitility dependencies from 3.1.2 to 4.0.3

pom.xml
This pull request closes strongbox/strongbox#1873
=> Issue 1873

pom.xml
This pull request closes strongbox/strongbox#1852
=> Issue 1852: Upgrade our JUnit dependencies from 5.4.0 to 5.7.0

pom.xml
This pull request closes strongbox/strongbox#1916
=> Issue 1916: update version of jsonschema2pojo needed in strongbox-npm-metadata 

pom.xml
This pull request closes strongbox/strongbox#1862
=> Issue 1862: Update org.apache.commons:commons-collections4 from version 4.3 to 4.4

pom.xml
This pull request closes strongbox/strongbox#1932
=> Updating gmavenplus-plugin for issue 1923

pom.xml
Closes strongbox/strongbox#1775
=> issues/1775: Upgrade to Cassandra to 4.0-beta2

pom.xml
This pull request closes strongbox/strongbox#1943
=> issues-1943: fixed parent pom version

pom.xml
This pull request closes strongbox/strongbox#1849
=> issues-1849: remove ehcache dependencies

pom.xml
This pull request closes strongbox/strongbox#1942.
=> Issue 1942: Add explicit versions for the plugins that are missing such in the strongbox-parent

pom.xml
This pull request closes strongbox/strongbox#1851
=> Issue 1851: Upgrade org.apache.httpcomponents:httpclient to 4.5.13

pom.xml
This pull request closes strongbox/strongbox#1847
=> Issue 1847: Upgrade commons-beanutils from 1.9.3 to 1.9.4

pom.xml
This pull request closes strongbox/strongbox#
=> Required Java version message fix for Maven enforcer plugin
